name: Run all Gradle integration tests and report errors to Slack channel

on:
  workflow_call:
    inputs:
      ignore_modules_regex:
        description: Regex of modules to ignore, e.g. 'utils/.*'.
        type: string
        required: false
        default: ""
      ignore_modules:
        description: Comma-separated list of relative paths to ignore. Must include dot at start of relative path, e.g. `., ./system/alpha`.
        type: string
        required: false
        default: ""
      build_and_inttest_cmd:
        description: Command to run for each module
        type: string
        required: false
        default: "./gradlew inttest"

    secrets:
      slack_webhook_url:
        description: A Slack Webhook URL for posting to a Slack channel
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REF: ${{ github.inputs.ref }}

jobs:
  find-modules:
    name: Find gradle modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find gradle modules
        id: find-gradle-modules
        uses: svvsaga/github-actions-public/find-gradle-module-changes@v9.0.0
        with:
          include_all: true
          ignore_modules_regex: ${{ inputs.ignore_modules_regex }}
          ignore_modules: ${{ inputs.ignore_modules }}
    outputs:
      matrix: ${{ steps.find-gradle-modules.outputs.matrix }}
      has_results: ${{ steps.find-gradle-modules.outputs.has_results }}

  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: find-modules
    if: needs.find-modules.outputs.has_results == 'true'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find-modules.outputs.matrix) }}
    defaults:
      run:
        working-directory: ${{ matrix.path }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Read integration testing config
        id: read-integration-testing-config
        uses: svvsaga/github-actions-public/read-integration-testing-config@v9.0.0
        with:
          cwd: ${{ matrix.path }}

      - name: Setup Google Cloud SDK with workload identity federation
        uses: svvsaga/github-actions-public/setup-gcloud-with-workload-identity@v16.0.1
        with:
          service_account: ${{ steps.read-integration-testing-config.outputs.service_account }}
          project_id: ${{ steps.read-integration-testing-config.outputs.workload_identity_project_id }}
          project_number: ${{ steps.read-integration-testing-config.outputs.workload_identity_project_number }}

      - name: Gradle build and integration test
        id: build-and-inttest
        uses: nick-fields/retry@3e91a01664abd3c5cd539100d10d33b9c5b68482
        continue-on-error: true
        with:
          timeout_minutes: 10
          max_attempts: 2
          retry_on: error
          command: ${{ inputs.build_and_inttest_cmd }}

      - name: Send integration test errors to Slack channel
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # Corresponding to v1.23.0
        if: steps.build-and-inttest.outcome == 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
        with:
          payload: |
            {
              "project_name": "${{ matrix.folder }}",
              "github_run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
      - name: Fail job if integration tests fail
        if: steps.build-and-inttest.outcome == 'failure'
        run: exit 1